# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = [workspace 6 silent] uwsm app -- easyeffects
exec-once = [workspace 6 silent] uwsm app -- blueman-manager
exec-once = [workspace 2 silent] uwsm app -- ghostty
exec-once = [workspace 1 silent] uwsm app -- zen-browser

